{application,gen_state_machine,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"An Elixir wrapper for gen_statem."},
              {modules,['Elixir.GenStateMachine',
                        'Elixir.GenStateMachine.Application',
                        'Elixir.GenStateMachine.Translator']},
              {registered,[]},
              {vsn,"3.0.0"},
              {mod,{'Elixir.GenStateMachine.Application',[]}}]}.
